---
- name: Create mount point
  file:
     path: '{{ mount_point }}'
     state: directory
     owner: root
     group: root
     mode: 0000
- name: Format volume
  filesystem:
     dev: '{{ device_name }}'
     fstype: ext4
     opts: '-v -t ext4 -I 128 -b 4096 -m 0 -E lazy_itable_init=0,lazy_journal_init=0,root_owner={{ vibes_uid }}:{{ vibes_gid }}'
- name: Mount volume
  mount:
     src: '{{ device_name }}'
     path: '{{ mount_point }}'
     state: mounted
     fstype: ext4
- name: Set volume ownership
  file:
     dest: '{{ mount_point }}'
     recurse: yes
     owner: vibes
     group: vibes
     mode: u=rwx,g=rx,o=rx
- name: Create required directories
  file:
     path: '{{ mount_point }}/{{ item }}'
     state: directory
     owner: '{{ vibes_uid }}'
     group: '{{ vibes_gid }}'
     mode: u=rwx,g=rx,o=rx
  with_items:
     - 'builds'
     - '.overlayfs'
- name: Unmount volume
  mount:
     path: '{{ mount_point }}'
     state: unmounted
