---
version: 0.2

phases:
   install:
      commands:
         - cd lambda
         - go get -v -d -- ./...
   build:
      commands:
         - GOOS=linux GOARCH=amd64 go build -o build -- build.go
         - zip -9 build.zip -- build
         - cd ../cfn
         - aws cloudformation package --template-file main.yaml --output-template-file main-packaged.yaml --s3-bucket "${BUCKET}" --s3-prefix main
         - mv -T -- main-packaged.yaml main.yaml

artifacts:
   files:
      - cfn/*.yaml
      - lambda/*.zip
   discard-paths: no
