---
version: 0.2

phases:
   install:
      commands:
         - cd lambda
         - go get -v -d -- ./...
   build:
      commands:
         - env
         - GOOS=linux GOARCH=amd64 go build -x -ldflags '-s -w' -o build -- build.go
         - zip -9 build.zip -- build
         - cd ../cfn
         - aws cloudformation package --template-file main.yaml --output-template-file main-packaged.yaml --s3-bucket "${BUCKET}" --s3-prefix lambda/main
         - mv -T -- main-packaged.yaml main.yaml

artifacts:
   base-directory: cfn
   files:
      - '*.yaml'
   discard-paths: no
