---
version: 0.2

phases:
   install:
      commands:
         - cd lambda
         - go get -v -d -- ./...
   build:
      commands:
         - env
         - |
            for lambda in *.py
            do
                zip -9 "${lambda%.py}.zip" -- "${lambda}"
            done
         - |
            for lambda in *.go
            do
                output="${lambda%.go}.exe"
                GOOS=linux GOARCH=amd64 go build -x -ldflags '-s -w' -o "${output}" -- "${lambda}"
                zip -9 "${lambda%.go}.zip" -- "${output}"
            done
         - cd ../cfn
         - mkdir pkg
         - |
            for template in *.yaml
            do
                aws cloudformation package --template-file "${template}" --output-template-file "pkg/${template}" --s3-bucket "${BUCKET}" --s3-prefix artifacts
            done

artifacts:
   base-directory: cfn/pkg
   files:
      - '*.yaml'
   discard-paths: yes
