---
version: 0.2

phases:
   build:
      commands:
         #- curl -sS -o ec2/worker/ansible/files/get-pip.py 'https://bootstrap.pypa.io/get-pip.py'
         - aws ssm put-parameter --overwrite --name /music/volume --type String --value 'hello'
         #- cd ec2/volume
         #- packer build -color=false template.json
         #- aws ssm put-parameter --overwrite --name /music/volume --type String --value "$(jq -r '.builds[0].artifact_id' manifest.json)"
