---
version: 0.2

phases:
   build:
      commands:
         - echo curl -sS -o ec2/worker/ansible/files/get-pip.py 'https://bootstrap.pypa.io/get-pip.py'
         - packer build -color=false ec2/volume/template.json
