---
- name: Update system software
  pacman:
     update_cache: yes
     upgrade: yes
- name: Install required packages
  pacman:
     name: '{{ item }}'
     state: present
  with_items:
     - tup
- name: Format EBS volume
  filesystem:
     dev: '{{ dev }}'
     fstype: '{{ fs_type }}'
- name: Create working volume mount point
  file:
     path: '{{ mount_point }}'
     state: directory
     owner: music
     group: music
     mode: u=rw,g=r
- name: Mount EBS volume
  mount:
     state: mounted
     src: '{{ dev }}'
     fstype: '{{ fs_type }}'
     path: '{{ mount_point }}'
     boot: no
- name: Initialize tup database
  command: tup init
  chdir: '{{ mount_point }}'
  become_user: music
- name: Upload tup settings for music project
  copy:
     src: tup.ini
     dest: '{{ mount_point }}/.tup/options'
  become_user: music
- name: Upload build code
  copy:
     src: tup
     dest: '{{ mount_point }}'
  become_user: music
- name: Unmount EBS volume
  mount:
     state: unmounted
     path: '{{ mount_point }}'
