---
- name: Update system software
  pacman:
     update_cache: yes
     upgrade: yes
- name: Install required packages
  pacman:
     name: '{{ item }}'
     state: present
  with_items:
     - aws-cli
     - e2fsprogs
     - f2fs-tools
     - openssh
     - python
     - tup
     - xfsprogs
- import_tasks: vibes-user.yaml
