---
- name: Update system software
  pacman:
     update_cache: yes
     upgrade: yes
- name: Install required packages
  pacman:
     name: '{{ item }}'
     state: present
  with_items:
     - e2fsprogs
     - f2fs-tools
     - tup
     - xfsprogs
- name: Download pip installation script
  get_url:
     url: 'https://bootstrap.pypa.io/get-pip.py'
     dest: /tmp/get-pip.py
- name: Install pip
  command: python /tmp/get-pip.py
- name: Install AWS CLI
  pip:
     name: awscli
     state: present
- name: Upload volume preparation scripts
  copy:
     src: 'prepare_volume-{{ item }}.sh'
     dest: '/usr/local/bin/music-prepare_volume-{{ item }}'
     owner: root
     group: root
     mode: u=rwx,g=rx,o=rx
  with_items:
     - sources
     - builds
- name: Create /usr/local/share/music folder
  file:
     path: /usr/local/share/music
     state: directory
     owner: root
     group: root
     mode: u=rw,g=rw,o=r
- name: Upload sources bucket name
  template:
     src: 'sources_bucket'
     dest: '/usr/local/share/music/sources_bucket'
     owner: root
     group: root
     mode: u=rw,g=r,o=r
- name: Create mount points for volumes
  file:
     path: '/mnt/music/{{ item }}'
     state: directory
     owner: root
     group: root
     mode: 0000
  with_items:
     - sources
     - builds
