---
- name: Update system software
  pacman:
     update_cache: yes
     upgrade: yes
- name: Install required packages
  pacman:
     name: '{{ item }}'
     state: present
  with_items:
     - e2fsprogs
     - f2fs-tools
     - openssh
     - python
     - tup
     - xfsprogs
- name: Download pip installation script
  get_url:
     url: 'https://bootstrap.pypa.io/get-pip.py'
     dest: /tmp/get-pip.py
- name: Install pip
  command: python /tmp/get-pip.py
- name: Install AWS CLI
  pip:
     name: awscli
     state: present
