---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
   CodeRepository:
      Type: 'AWS::CodeCommit::Repository'
      Properties:
         RepositoryName: music
         RepositoryDescription: 'AWS-based music compilation system.'
   SourcesBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
         Tags:
            -
               Key: music
               Value: sources
Outputs:
   CodeRepositoryArn:
      Description: 'ARN of the code repository.'
      Value: !GetAtt CodeRepository.Arn
      Export:
         Name: music-CodeRepositoryArn
   CodeRepositoryCloneUrlHttp:
      Description: 'HTTP clone URL of the code repository.'
      Value: !GetAtt CodeRepository.CloneUrlHttp
      Export:
         Name: music-CodeRepositoryCloneUrlHttp
   SourcesBucket:
      Description: 'Name of the source bucket.'
      Value: !Ref SourcesBucket
      Export:
         Name: music-SourcesBucket
   SourcesBucketArn:
      Description: 'ARN of the source bucket.'
      Value: !GetAtt SourcesBucket.Arn
      Export:
         Name: music-SourcesBucketArn
