---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
   SourceBucket:
      Type: 'AWS::S3::Bucket'
   SourceRepository:
      Type: 'AWS::CodeCommit::Repository'
      Properties:
         RepositoryName: music
         RepositoryDescription: 'AWS-based music compilation system.'
Outputs:
   SourceBucket:
      Description: 'Name of the source bucket.'
      Value: !Ref SourceBucket
      Export:
         Name: music-SourceBucket
   SourceBucketArn:
      Description: 'ARN of the source bucket.'
      Value: !GetAtt SourceBucket.Arn
      Export:
         Name: music-SourceBucketArn
   SourceRepositoryArn:
      Description: 'ARN of the source repository.'
      Value: !GetAtt SourceRepository.Arn
      Export:
         Name: music-SourceRepositoryArn
   SourceRepositoryCloneUrlHttp:
      Description: 'HTTP clone URL of the source repository.'
      Value: !GetAtt SourceRepository.CloneUrlHttp
      Export:
         Name: music-SourceRepositoryCloneUrlHttp
