---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
   SourcesBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
         Tags:
            -
               Key: vibes
               Value: sources
Outputs:
   SourcesBucket:
      Description: 'Name of the source bucket.'
      Value: !Ref SourcesBucket
      Export:
         Name: vibes-SourcesBucket
   SourcesBucketArn:
      Description: 'ARN of the source bucket.'
      Value: !GetAtt SourcesBucket.Arn
      Export:
         Name: vibes-SourcesBucketArn
