---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
   Profile:
      Description: 'Name of the profile.'
      Type: String
   Config:
      Description: 'Tup configuration associated to the profile. A comma-delimited list in which each element represents a line in the tup.config file.'
      Type: CommaDelimitedList
Resources:
   ConfigParameter:
      Type: 'AWS::SSM::Parameter'
      Properties:
         Name: !Sub '/vibes/profiles/${Profile}'
         Type: String
         Value: !Join [ "\n" , [ !Join [ "\n" , !Ref Config ] , '' ] ]
