---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
   Profile:
      Type: String
      Description: Name of the profile.
Resources:
   ConfigParameter:
      Type: 'AWS::SSM::Parameter'
      Properties:
         Name: !Sub '/music/profiles/${Profile}/config'
         Type: String
         Value: "\n"
