---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Resources representing a tup-vibes profile.'
Parameters:
   Name:
      Description: 'Name of the profile.'
      Type: String
   Format:
      Description: 'Format into which to encode the collection.'
      Type: String
   Encoder:
      Description: 'Encoder program with which to encode the collection.'
      Type: String
   ExtraConfig:
      Description: 'Additional tup configuration associated with the profile. A comma-delimited list in which each element represents a line in the tup.config file.'
      Type: CommaDelimitedList
Metadata:
   AWS::CloudFormation::Interface:
      ParameterGroups:
         -
            Label:
               default: General
            Parameters:
               - Name
         -
            Label:
               default: Configuration
            Parameters:
               - Format
               - Encoder
               - ExtraConfig
      ParameterLabels:
         Encoder:
            default: Encoder
         ExtraConfig:
            default: Extra configuration
         Format:
            default: Format
         Name:
            default: Name
Resources:
   ConfigParameter:
      Type: 'AWS::SSM::Parameter'
      Properties:
         Name: !Sub '/vibes/profiles/${Name}'
         Description: !Sub 'Tup configuration associated with the ${Name} profile.'
         Type: String
         Value: !Sub
            - "CONFIG_FORMAT=${Format}\nCONFIG_ENCODER=${Encoder}\n${extra}\n"
            - extra: !Join [ "\n" , !Ref ExtraConfig ]
