---
- name: Update system and install required packages
  pacman:
     name: '{{ item }}'
     state: present
     update_cache: yes
     upgrade: yes
  with_items:
     - rsync
- name: Enable rsync server
  systemd:
     name: rsyncd
     enabled: yes
- name: Upload rsync server configuration
  template:
     src: 'rsyncd.conf.j2'
     dest: '/etc/rsyncd.conf'
     owner: root
     group: root
     mode: u=rw,g=r,o=r
