---
- name: Provision AMI
  hosts: all
  gather_facts: false
  tasks:
     - name: lala
       command: echo hi
     - name: Update system and install required packages
       pacman:
          name: '{{ item }}'
          state: present
          update_cache: yes
          upgrade: yes
       with_items:
          - openssh
          - rsync
