---
- name: Provision AMI
  hosts: all
  tasks:
     - name: Run dist-upgrade
       apt:
          update_cache: yes
          upgrade: dist
     - name: Install required packages
       apt:
          name: '{{ item }}'
       with_items:
          - rsync
---
- name: Provision AMI
  hosts: all
  gather_facts: false
  tasks:
     - name: lala
       command: echo hi
     - name: Update system and install required packages
       pacman:
          name: '{{ item }}'
          state: present
          update_cache: yes
          upgrade: yes
