---
version: 0.2

phases:
   build:
      commands:
         - aws s3 cp --quiet --recursive "s3://${SOURCE_BUCKET}" codebuild/run/build
         - mv -ft codebuild/run/build -- tup/*
         - cd codebuild/run/build
         - mkdir build
         - aws --query 'Parameter.Value' --output text ssm get-parameter --name "/music/profiles/${PROFILE}/config" >build/tup.config
         - tup build
         - rm -- build/tup.config

artifacts:
   base-directory: codebuild/run/build/build
   files:
      - '**/*'
   discard-paths: no
