---
version: 0.2

env:
   parameter-store:
      INSTANCE_AMI: '/vibes/ec2/ami/volmgr'

phases:
   build:
      commands:
         - cd ec2
         - NOW="$(date +%s)"
         - SIZE="$(( $(aws --query 'Datapoints[0].Average' --output text cloudwatch get-metric-statistics --namespace AWS/S3 --start-time "$((${NOW}-86400))" --end-time "${NOW}" --period 86400 --statistics Average --metric-name BucketSizeBytes --dimensions "Name=BucketName,Value=${SOURCES_BUCKET}" Name=StorageType,Value=StandardStorage | cut -d . -f 1) / 1073741824 + 2 ))"
         - |
            echo "Sources bucket size: ${SIZE} GiB"
         #  User variables do not seem to play well with numeric parameters
         - bash -c 'packer build <(jq -c ".builders[0].ebs_volumes[0].volume_size=${SIZE}" -- template-ebs-sources.json)'
         - cat -- manifest.json
         - |
            VOLUME_ID="$(jq -r '.builds[0].artifact_id' -- manifest.json | cut -d : -f 2)"
         - SNAPSHOT_ID="$(aws --query 'SnapshotId' --output text ec2 create-snapshot --volume-id "${VOLUME_ID}" --tag-specifications 'ResourceType=snapshot,Tags=[{Key=vibes,Value=sources}]')"
         - WORKER_LAUNCH_TEMPLATE_LAST="$(aws --query 'LaunchTemplates[0].LatestVersionNumber' --output text ec2 describe-launch-templates --launch-template-ids "${WORKER_LAUNCH_TEMPLATE}")"
         - WORKER_LAUNCH_TEMPLATE_NEW="$(aws --query 'LaunchTemplateVersion.VersionNumber' --output text ec2 create-launch-template-version --launch-template-id "${WORKER_LAUNCH_TEMPLATE}" --launch-template-data "$(aws --query 'LaunchTemplateVersions[0].LaunchTemplateData' --output json ec2 describe-launch-template-versions --launch-template-id ${WORKER_LAUNCH_TEMPLATE} --versions ${WORKER_LAUNCH_TEMPLATE_LAST} | jq -c ".BlockDeviceMappings[0].Ebs.SnapshotId=\"${SNAPSHOT_ID}\"")")"
         - |
            echo "Updated worker launch template version: $(aws --query 'LaunchTemplate.DefaultVersionNumber' --output text ec2 modify-launch-template --launch-template-id "${WORKER_LAUNCH_TEMPLATE}" --default-version "${WORKER_LAUNCH_TEMPLATE_NEW}")"
      finally:
         - aws ec2 delete-volume --volume-id "${VOLUME_ID}"
