---
version: 0.2

env:
   parameter-store:
      SSH_KEY: '/music/ec2/keys/packer'

phases:
   build:
      commands:
         - cd ec2
         - echo "${SSH_KEY}" >music-packer.pem
         - echo chmod 0600 music-packer.pem
         - curl -sS -o 'roles/worker/files/get-pip.py' 'https://bootstrap.pypa.io/get-pip.py'
         - packer build -color=false template-worker.json
         - |
             aws ec2 create-launch-template --launch-template-name music-server --type String --value "$(jq -r '.builds[0].artifact_id' manifest.json | cut -d : -f2)"
