---
version: 0.2

phases:
   build:
      commands:
         - cd ec2
         - NOW="$(date +%s)"
         - SIZE="$(( $(aws --query 'Datapoints[0].Average' --output text cloudwatch get-metric-statistics --namespace AWS/S3 --start-time "$((${NOW}-86400))" --end-time "${NOW}" --period 86400 --statistics Average --metric-name BucketSizeBytes --dimensions "Name=BucketName,Value=${SOURCES_BUCKET}" Name=StorageType,Value=StandardStorage | cut -d . -f 1) / 1073741824 + 2 ))"
         - |
            echo "Sources bucket size: ${SIZE} GiB"
         #  User variables do not seem to play well with numeric parameters
         - bash -c 'packer build <(jq -c ".builders[0].ebs_volumes[0].volume_size=${SIZE}" -- template-ebs-sources.json)'
         - cat -- manifest.json
         - |
            SOURCES_VOLUME_ID="$(jq -r '.builds[0].artifact_id' -- manifest.json | cut -d : -f 2)"
         - SOURCES_SNAPSHOT_ID="$(aws --query 'SnapshotId' --output text ec2 create-snapshot --volume-id "${SOURCES_VOLUME_ID}")"
         - aws ssm put-parameter --overwrite --name '/vibes/ec2/snapshot/sources' --type String --value "${SOURCES_SNAPSHOT_ID}"
         - LAUNCH_TEMPLATE_LAST="$(aws --query 'LaunchTemplates[0].LatestVersionNumber' --output text ec2 describe-launch-templates --launch-template-ids "${LAUNCH_TEMPLATE}")"
         - LAUNCH_TEMPLATE_NEW="$(aws --query 'LaunchTemplateVersion.VersionNumber' --output text ec2 create-launch-template-version --launch-template-id "${LAUNCH_TEMPLATE}" --source-version "${LAUNCH_TEMPLATE_LAST}" --launch-template-data "$(sed -e "s/%SOURCES_SNAPSHOT_ID%/${SOURCES_SNAPSHOT_ID}/g;s/%BUILDS_SNAPSHOT_ID%/${BUILDS_SNAPSHOT_ID}/g" -- lt-worker.json)")"
         - |
            echo "Updated worker launch template version: $(aws --query 'LaunchTemplate.DefaultVersionNumber' --output text ec2 modify-launch-template --launch-template-id "${LAUNCH_TEMPLATE}" --default-version "${LAUNCH_TEMPLATE_NEW}")"
