---
version: 0.2

phases:
   build:
      commands:
         - cd ec2
         - mkdir -p roles/volmgr/files
         - curl -sS -o 'roles/volmgr/files/get-pip.py' 'https://bootstrap.pypa.io/get-pip.py'
         - packer build -color=false -only=volmgr template-ami.json
         - |
            echo "Updated launch template version: $(aws --query 'LaunchTemplate.DefaultVersionNumber' --output text ec2 modify-launch-template --launch-template-id "${LAUNCH_TEMPLATE}" --default-version "$(aws --query 'LaunchTemplateVersion.VersionNumber' --output text ec2 create-launch-template-version --launch-template-id "${LAUNCH_TEMPLATE}" --source-version "$(aws --query 'LaunchTemplates[0].DefaultVersionNumber' --output text ec2 describe-launch-templates --launch-template-ids "${LAUNCH_TEMPLATE}")" --launch-template-data "{\"ImageId\":\"$(jq -r '.builds[0].artifact_id' manifest.json | cut -d : -f2)\"}")")"
