---
version: 0.2

phases:
   build:
      commands:
         - cd ec2
         - packer build template-ami.json
         - cat -- manifest.json
         - |
            AMI_ID="$(jq -r '.builds[0].artifact_id' -- manifest.json | cut -d : -f 2)"
         - |
            if test "$NAME" = volmgr ; then aws ssm put-parameter --overwrite --name "/vibes/ec2/ami/${NAME}" --type String --value "${AMI_ID}" ; else echo "Updated ${NAME} launch template version: $(aws --query 'LaunchTemplate.DefaultVersionNumber' --output text ec2 modify-launch-template --launch-template-id "${LAUNCH_TEMPLATE}" --default-version "$(aws --query 'LaunchTemplateVersion.VersionNumber' --output text ec2 create-launch-template-version --launch-template-id "${LAUNCH_TEMPLATE}" --source-version "$(aws --query 'LaunchTemplates[0].LatestVersionNumber' --output text ec2 describe-launch-templates --launch-template-ids "${LAUNCH_TEMPLATE}")" --launch-template-data "{\"ImageId\":\"${AMI_ID}\"}")")" ; fi
