---
- name: Update system software
  pacman:
     update_cache: yes
     upgrade: yes
- name: Install required packages
  pacman:
     name: '{{ item }}'
     state: present
  with_items:
     - e2fsprogs
     - f2fs-tools
     - flac
     - git
     - lame
     - opus-tools
     - tup
     - vorbis-tools
     - xfsprogs
- name: Set up git for CodeCommit access
  git_config:
     scope: system
     name: '{{ item.name }}'
     value: '{{ item.value }}'
  loop:
     -
        name: credential.helper
        value: '!aws codecommit credential-helper $@'
     -
        name: credential.UseHttpPath
        value: true
- name: Download build code
  git:
     repo: '{{ code_repo }}'
     dest: '{{ code_dir }}'
     clone: yes
  become_user: music
- name: Enable full dependency tracking for tup
  file:
     path: /usr/bin/tup
     mode: +s
- name: Upload systemd service units
  template:
     src: 'music-{{ item }}.service.j2'
     dest: '/etc/systemd/system/music-{{ item }}.service'
     owner: root
     group: root
     mode: u=rw,g=r,o=r
  with_items:
     - build
     - monitor
#- name: Enable tup monitor service
#  systemd:
#     name: music-monitor
#     enabled: yes
- name: Create mount points
  file:
     path: '{{ item }}'
     state: directory
     owner: root
     group: root
     mode: 0000
  with_items:
     - '{{ sources_mount_point }}'
     - '{{ builds_mount_point }}'
- name: Create OverlayFS mount point
  file:
     path: '{{ work_dir }}'
     state: directory
     owner: music
     group: music
     mode: u=rwx,g=rwx,o=rx
- name: Set up work directory
  mount:
     state: present
     src: overlay
     fstype: overlay
     opts: 'lowerdir={{ sources_mount_point }}:{{ code_dir }}/tup:{{ profiles_dir }},upperdir={{ builds_mount_point }}/builds,workdir={{ builds_mount_point }}/.overlayfs'
     path: '{{ work_dir }}'
- name: Upload tup settings
  copy:
     src: tup.ini
     dest: '{{ music_home }}/.tupoptions'
  become_user: music
