---
- name: Update system software
  pacman:
     update_cache: yes
     upgrade: yes
- name: Install required packages
  pacman:
     name: '{{ item }}'
     state: present
  with_items:
     - e2fsprogs
     - f2fs-tools
     - flac
     - git
     - lame
     - opus-tools
     - tup
     - vorbis-tools
     - xfsprogs
- name: Enable full dependency tracking for tup
  file:
     path: /usr/bin/tup
     mode: +s
- name: Install pip
  script: get-pip.py
- name: Install AWS CLI
  pip:
     name: awscli
     state: present
- name: Determine systemd mount unit name for sources device
  command: 'systemd-escape --path {{ sources_mount_point }}'
  register: sources_mount_unit_name
- name: Upload systemd mount unit for sources device
  template:
     src: 'music-sources.mount.j2'
     dest: '/etc/systemd/system/{{ sources_mount_unit_name.stdout }}.mount'
     owner: root
     group: root
     mode: u=rw,g=r,o=r
- name: Determine systemd mount unit name for builds device
  command: 'systemd-escape --path {{ builds_mount_point }}'
  register: builds_mount_unit_name
- name: Upload systemd mount unit for builds device
  template:
     src: 'music-builds.mount.j2'
     dest: '/etc/systemd/system/{{ builds_mount_unit_name.stdout }}.mount'
     owner: root
     group: root
     mode: u=rw,g=r,o=r
- name: Upload systemd service units
  template:
     src: 'music-{{ item }}.service.j2'
     dest: '/etc/systemd/system/music-{{ item }}.service'
     owner: root
     group: root
     mode: u=rw,g=r,o=r
  with_items:
     - build
     - monitor
     - snapshot
     - sync
- name: Enable tup monitor service
  systemd:
     name: music-monitor
     enabled: yes
- name: Format sources volume
  filesystem:
     dev: '{{ sources_device_name }}'
     fstype: '{{ sources_fs_type }}'
- name: Format builds volume
  filesystem:
     dev: '{{ builds_device_name }}'
     fstype: '{{ builds_fs_type }}'
- name: Create mount points
  file:
     path: '{{ item }}'
     state: directory
     owner: root
     group: root
     mode: 0000
  with_items:
     - '{{ sources_mount_point }}'
     - '{{ builds_mount_point }}'
     - '{{ work_dir }}'
- name: Mount sources volume
  mount:
     state: mounted
     src: '{{ sources_device_name }}'
     fstype: '{{ sources_fs_type }}'
     path: '{{ sources_mount_point }}'
- name: Mount builds volume
  mount:
     state: mounted
     src: '{{ sources_device_name }}'
     fstype: '{{ sources_fs_type }}'
     path: '{{ sources_mount_point }}'
- name: Set up git for CodeCommit access
  git_config:
     scope: system
     name: '{{ item.name }}'
     value: '{{ item.value }}'
  loop:
     -
        name: credential.helper
        value: '!aws codecommit credential-helper $@'
     -
        name: credential.UseHttpPath
        value: true
- name: Download build code
  git:
     repo: '{{ code_repo }}'
     dest: '{{ code_dir }}'
     clone: yes
  become_user: music
- name: Create OverlayFS workdir
  file:
     path: '{{ builds_mount_point }}/.overlayfs'
     state: directory
     owner: root
     group: root
     mode: 0000
- name: Set up work directory
  mount:
     state: mounted
     src: overlay
     fstype: overlay
     opts: 'lowerdir={{ sources_mount_point }}:{{ code_dir }}/tup:{{ profiles_dir }},upperdir={{ builds_mount_point }},workdir={{ builds_mount_point }}/.overlayfs'
     path: '{{ work_dir }}'
- name: Initialize tup database
  command: tup init
  args:
     chdir: '{{ work_dir }}'
  become_user: music
- name: Upload tup settings for music project
  copy:
     src: tup.ini
     dest: '{{ work_dir }}/.tup/options'
  become_user: music
- name: Unmount volumes
  mount:
     state: unmounted
     path: '{{ item }}'
  with_items:
     - '{{ sources_mount_point }}'
     - '{{ builds_mount_point }}'
