---
- name: Update system and install required packages
  pacman:
     name: '{{ item }}'
     state: present
     update_cache: yes
     upgrade: yes
  with_items:
     - flac
     - lame
     - opus-tools
     - tup
     - vorbis-tools
- name: Enable full dependency tracking for tup
  file:
     path: /usr/bin/tup
     mode: +s
- name: Install pip
  script: get-pip.py
- name: Install AWS CLI
  pip:
     name: awscli
     state: present
- name: Create working volume mount point
  file:
     path: '{{ mount_point }}'
     state: directory
     owner: music
     group: music
     mode: u=rw,g=r
- name: Determine systemd mount unit name
  command: 'systemd-escape --path {{ mount_point }}'
  register: mount_unit_name
- name: Upload systemd mount unit
  template:
     src: 'music.mount.j2'
     dest: '/etc/systemd/system/{{ mount_unit_name.stdout }}.mount'
     owner: root
     group: root
     mode: u=rw,g=r,o=r
- name: Upload systemd service unit
  template:
     src: 'music.service.j2'
     dest: '/etc/systemd/system/music.service'
     owner: root
     group: root
     mode: u=rw,g=r,o=r
- name: Enable tup monitor service
  systemd:
     name: music
     enabled: yes
